### ISSUE TITLE
Cannot set autoHeight to false in iframe embed

### ISSUE THREAD

**Issue by mcous** [porsager/flems.io#23] opened 2020-04-20 03:05 UTC
Hi! I've been playing around with this project this weekend and it's seriously cool! I'm hoping to use it to add some example playgrounds to a documentation site I'm working on.

I'm working in React, so for ease + speed I tried embedding `flems.io` links in `<iframe>`s for some good old-fashioned iframe inception, but I ran into a problem with the height top level `.flems` wrapper.

From reading the flems module source code and inspecting the `flems.io` source, I _think_ I'm reading that if `flems.io` is loaded in an iframe, it forces the `options.autoHeight` option to `true`, even if I try to override it to `false` in `state`. This is a problem for me, because I want to specify an explicit height of the editor via the iframe's height.

[Demo of the problem on flems.io](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYAeACaEAbgAIIcGmDABeADogA7lBoAHLSSiqAfMqrDC+TQymia7GgFpWMGAGsVBCyVUy5Ct6JJ0MIZSxsIA9GYeRiZh4hIGIHhgJKQQ7IR85EggAMxIAGwgAL4Y1PSM2cwAVuQ8fAJC2bxUYOxS5uVSilYwEACuDPzMAI59egCeAMopJGkwUAAUAOQo1rYOTq6qHQyq2EsAlMbGOyTMYFAQXVJLHOxaYEhhYfikdGDMGWEAxGiKS1IANRSAAyAC1JuwoIQqABzZi8OhaKBkMAAFRgAFEqLx-KIAKoAJQAkgBhGBIviCdgLYxSKQAKUmAHkAHLnKEw2FmcYLYBSGh9dgwAASJEIsI4SHaNDgySkRQO9LpUgOiRAiK0xD0TAARjRdSl1clUulMkwACxIHLFUogWgMJgIhTq5oNdhOjTaXRQKTAFVqQiidisaUARjQaAApABuFWscWS9jSgBMAFZ8loAB5xqhFY5UZj+QJ+gNBkPhyOx+OJqVSCPR3P03XzfxQaVoJtSFtZuxgVg0UQwNTh7P1scpsdoKRQWH6haYKSL5fMHIHXNFY0zNIZFpMFNIMOFIq4EBwGHOLKUe3lJhwABefc5cPVfSgiGydweTzCfSoWmceFETCB8n2hOEAAEw2YC0YJAwhdTAEDH1acD4RqdV2HGXQmEgaEtA9E8iiAA)

Minified code from my browser's "View Source" where I think `autoHeight` is forced to `true`

```js
    var Cn = window.self !== window.top
      , An = window.location.pathname;
    window.m = bt;
    var En, zn, Tn = (En = 0 === location.hash.indexOf("#0=") ? function(e) {
        var t;
        try {
            t = JSON.parse(H.decompressFromEncodedURIComponent(e))
        } catch (e) {}
        t || (window.alert("The url appears to be cut short or malformed.\n\nLoading empty Flems."),
        window.history.replaceState(void 0, void 0, "/"));
        return t || {}
    }(location.hash.slice(3)) : {},
    (zn = Lt(Ht(), En)).files.forEach(function(e) {
        return e.id = Math.random()
    }),
    zn.links.forEach(function(e) {
        return e.id = Math.random()
    }),
    zn);
    Tn.autoHeight = Cn,
    Tn.autoFocus = !Cn,
    Tn.shareButton = Cn;
```

I'm not sure if [this thread](https://github.com/porsager/flems/issues/53#issuecomment-394005581) is applicable here but I was reading through it to try to figure out if I was doing something wrong. Also, this issue doesn't appear to be present on `next.flems.io`.

**Comment by porsager** [comment] 2020-04-21 07:20
Hey, thanks a lot ! 

That sure looks like a regression. I'll look closer and see if I can fix it soon 👍

**Comment by porsager** [comment] 2020-04-22 05:38
Got it fixed now ;)

**Closed by porsager** 2020-04-22 05:38 UTC
Labels: bug
